name 'nanliu-staging'
version '0.3.0'

author 'nanliu'
license 'Apache License Version 2.0'
project_page 'https://github.com/nanliu/puppet-staging'
source 'git@github.com:nanliu/puppet-staging.git'
summary 'File Staging'
description 'Manages file staging.'
